version: '3'
services:
  patientjournal:
    build:
      context: ./
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://130.237.83.249:2781/patientjournal
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: wiljamniklas