apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullstack-patientjournal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fullstack-patientjournal
  template:
    metadata:
      labels:
        app: fullstack-patientjournal
    spec:
      containers:
        - name: fullstack-patientjournal
          image: wiljam/fullstack-patientjournal:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/patientjournal
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: wiljamniklas
